// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CreateDirectory(arg1:string):Promise<void>;

export function CreateFile(arg1:string):Promise<void>;

export function DeleteNode(arg1:string):Promise<void>;

export function GetDirectory(arg1:string):Promise<domain.FileNode>;

export function OpenNote(arg1:string):Promise<domain.Note>;

export function ReadImageBase64(arg1:string):Promise<string>;

export function RenameNode(arg1:string,arg2:string):Promise<void>;

export function SaveImage(arg1:string,arg2:string):Promise<void>;

export function SaveNote(arg1:string,arg2:string):Promise<void>;

export function StartTerminal():Promise<void>;

export function StopTerminal():Promise<void>;

export function WriteTerminal(arg1:string):Promise<void>;
