// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDirectory(arg1) {
  return window['go']['app']['App']['GetDirectory'](arg1);
}

export function OpenNote(arg1) {
  return window['go']['app']['App']['OpenNote'](arg1);
}

export function SaveNote(arg1, arg2) {
  return window['go']['app']['App']['SaveNote'](arg1, arg2);
}
