// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CreateFileInWorkspace(arg1:string):Promise<domain.FileNode>;

export function CreateFolderInWorkspace(arg1:string):Promise<domain.FileNode>;

export function DeleteNode(arg1:string):Promise<domain.FileNode>;

export function GenerateAIContent(arg1:string):Promise<string>;

export function GetDirectory(arg1:string):Promise<domain.FileNode>;

export function GetGroqAPIKey():Promise<string>;

export function ImportImage():Promise<string>;

export function OpenNote(arg1:string):Promise<domain.Note>;

export function OpenWorkspace():Promise<domain.FileNode>;

export function ReadImageBase64(arg1:string):Promise<string>;

export function RefreshWorkspace():Promise<domain.FileNode>;

export function RenameNode(arg1:string,arg2:string):Promise<domain.FileNode>;

export function SaveImage(arg1:string,arg2:string):Promise<string>;

export function SaveImageWithPath(arg1:string,arg2:string):Promise<void>;

export function SaveNote(arg1:string):Promise<void>;

export function SearchVault(arg1:string):Promise<Array<domain.FileNode>>;

export function SelectFolder():Promise<string>;

export function SetGroqAPIKey(arg1:string):Promise<void>;

export function StartTerminal():Promise<void>;

export function StopTerminal():Promise<void>;

export function WriteTerminal(arg1:string):Promise<void>;
