// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDirectory(arg1) {
  return window['go']['app']['App']['CreateDirectory'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['app']['App']['CreateFile'](arg1);
}

export function DeleteNode(arg1) {
  return window['go']['app']['App']['DeleteNode'](arg1);
}

export function GetDirectory(arg1) {
  return window['go']['app']['App']['GetDirectory'](arg1);
}

export function OpenNote(arg1) {
  return window['go']['app']['App']['OpenNote'](arg1);
}

export function ReadImageBase64(arg1) {
  return window['go']['app']['App']['ReadImageBase64'](arg1);
}

export function RenameNode(arg1, arg2) {
  return window['go']['app']['App']['RenameNode'](arg1, arg2);
}

export function SaveImage(arg1, arg2) {
  return window['go']['app']['App']['SaveImage'](arg1, arg2);
}

export function SaveNote(arg1, arg2) {
  return window['go']['app']['App']['SaveNote'](arg1, arg2);
}

export function StartTerminal() {
  return window['go']['app']['App']['StartTerminal']();
}

export function StopTerminal() {
  return window['go']['app']['App']['StopTerminal']();
}

export function WriteTerminal(arg1) {
  return window['go']['app']['App']['WriteTerminal'](arg1);
}
