// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFileInWorkspace(arg1) {
  return window['go']['app']['App']['CreateFileInWorkspace'](arg1);
}

export function CreateFolderInWorkspace(arg1) {
  return window['go']['app']['App']['CreateFolderInWorkspace'](arg1);
}

export function DeleteNode(arg1) {
  return window['go']['app']['App']['DeleteNode'](arg1);
}

export function GenerateAIContent(arg1) {
  return window['go']['app']['App']['GenerateAIContent'](arg1);
}

export function GetDirectory(arg1) {
  return window['go']['app']['App']['GetDirectory'](arg1);
}

export function GetGroqAPIKey() {
  return window['go']['app']['App']['GetGroqAPIKey']();
}

export function ImportImage() {
  return window['go']['app']['App']['ImportImage']();
}

export function OpenNote(arg1) {
  return window['go']['app']['App']['OpenNote'](arg1);
}

export function OpenWorkspace() {
  return window['go']['app']['App']['OpenWorkspace']();
}

export function ReadImageBase64(arg1) {
  return window['go']['app']['App']['ReadImageBase64'](arg1);
}

export function RefreshWorkspace() {
  return window['go']['app']['App']['RefreshWorkspace']();
}

export function RenameNode(arg1, arg2) {
  return window['go']['app']['App']['RenameNode'](arg1, arg2);
}

export function SaveImage(arg1, arg2) {
  return window['go']['app']['App']['SaveImage'](arg1, arg2);
}

export function SaveImageWithPath(arg1, arg2) {
  return window['go']['app']['App']['SaveImageWithPath'](arg1, arg2);
}

export function SaveNote(arg1) {
  return window['go']['app']['App']['SaveNote'](arg1);
}

export function SearchVault(arg1) {
  return window['go']['app']['App']['SearchVault'](arg1);
}

export function SelectFolder() {
  return window['go']['app']['App']['SelectFolder']();
}

export function SetGroqAPIKey(arg1) {
  return window['go']['app']['App']['SetGroqAPIKey'](arg1);
}

export function StartTerminal() {
  return window['go']['app']['App']['StartTerminal']();
}

export function StopTerminal() {
  return window['go']['app']['App']['StopTerminal']();
}

export function WriteTerminal(arg1) {
  return window['go']['app']['App']['WriteTerminal'](arg1);
}
